// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * UI-facing event types sent over WebSocket to the frontend.
 *
 * Each variant maps to a specific UI component update. The enum is
 * internally tagged so the JSON shape is `{ "type": "TurnStarted", ... }`.
 *
 * Variant names are PascalCase to match the TypeScript `AppEvent.type`
 * discriminant values.
 */
export type AppEvent = { "type": "ThreadStarted", threadId: string, ts: bigint, } | { "type": "TurnStarted", turnId: string, sessionId: string, userPrompt: string, ts: bigint, } | { "type": "TurnComplete", turnId: string, 
/**
 * One of: "success", "error", "cancelled"
 */
status: string, ts: bigint, } | { "type": "CommandExecution", id: string, turnId: string, cmd: string, exitCode: number | null, stdout: string, stderr: string, ts: bigint, } | { "type": "McpToolCall", id: string, turnId: string, toolName: string, input: JsonValue, output: JsonValue | null, 
/**
 * One of: "success", "error"
 */
status: string, ts: bigint, } | { "type": "PatchApply", id: string, turnId: string, filename: string, diff: string, 
/**
 * One of: "success", "error"
 */
status: string, ts: bigint, } | { "type": "PlanUpdate", id: string, turnId: string, text: string, ts: bigint, };
