// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentState } from "./CollabAgentState";
import type { CollabStatus } from "./CollabStatus";
import type { CollabTool } from "./CollabTool";

/**
 * Collaborative tool call details
 */
export type CollabToolCallDetails = { tool: CollabTool, sender_thread_id: string, receiver_thread_ids: Array<string>, prompt: string | null, agents_states: { [key in string]?: CollabAgentState }, status: CollabStatus, };
