// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status for individual collaborative agents
 */
export type CollabAgentStatus = "pending_init" | "running" | "completed" | "errored" | "shutdown" | "not_found";
