// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of collaborative tool
 */
export type CollabTool = "spawn_agent" | "send_input" | "wait" | "close_agent";
