// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentStatus } from "./CollabAgentStatus";

/**
 * State of a collaborative agent
 */
export type CollabAgentState = { status: CollabAgentStatus, message: string | null, };
