// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "./ExecutionStatus";

/**
 * Command execution details
 */
export type CommandExecutionDetails = { command: string, status: ExecutionStatus, exit_code: number | null, aggregated_output: string, };
