// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Command evidence pointer.
 */
export type CommandEvidence = { command: string, exit_code: number | null, };
