// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputStream } from "./OutputStream";

/**
 * Delta details for streaming updates
 */
export type DeltaDetails = { "delta_type": "agent_message_delta", text_delta: string, } | { "delta_type": "command_output_delta", output_delta: string, stream: OutputStream, } | { "delta_type": "file_change_delta", output_delta: string, } | { "delta_type": "reasoning_delta", text_delta: string, };
