// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSource } from "./EventSource";

/**
 * Event pointer so summaries can map to source evidence.
 */
export type EventReference = { source: EventSource, source_event_type: string, timestamp: bigint, turn_id: string | null, item_id: string | null, };
