// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of the event
 */
export type EventSource = "exec_json" | "app_server_v2" | "rollout_replay";
