// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { ItemCompletedPayload } from "./ItemCompletedPayload";
import type { ItemDeltaPayload } from "./ItemDeltaPayload";
import type { ItemStartedPayload } from "./ItemStartedPayload";
import type { ItemUpdatedPayload } from "./ItemUpdatedPayload";
import type { ThreadStartedPayload } from "./ThreadStartedPayload";
import type { TurnCompletedPayload } from "./TurnCompletedPayload";
import type { TurnFailedPayload } from "./TurnFailedPayload";
import type { TurnStartedPayload } from "./TurnStartedPayload";

/**
 * Event payload with lifecycle semantics
 */
export type EventPayload = { "event_type": "thread_started" } & ThreadStartedPayload | { "event_type": "thread_closed" } | { "event_type": "turn_started" } & TurnStartedPayload | { "event_type": "turn_completed" } & TurnCompletedPayload | { "event_type": "turn_failed" } & TurnFailedPayload | { "event_type": "item_started" } & ItemStartedPayload | { "event_type": "item_updated" } & ItemUpdatedPayload | { "event_type": "item_completed" } & ItemCompletedPayload | { "event_type": "item_delta" } & ItemDeltaPayload | { "event_type": "error" } & ErrorPayload;
