// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * Individual file change
 */
export type FileChange = { path: string, kind: ChangeKind, };
