// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessageDetails } from "./AgentMessageDetails";
import type { CollabToolCallDetails } from "./CollabToolCallDetails";
import type { CommandExecutionDetails } from "./CommandExecutionDetails";
import type { ErrorDetails } from "./ErrorDetails";
import type { FileChangeDetails } from "./FileChangeDetails";
import type { McpToolCallDetails } from "./McpToolCallDetails";
import type { ReasoningDetails } from "./ReasoningDetails";
import type { TodoListDetails } from "./TodoListDetails";
import type { WebSearchDetails } from "./WebSearchDetails";

/**
 * Item-specific details
 */
export type ItemDetails = { "type": "agent_message" } & AgentMessageDetails | { "type": "reasoning" } & ReasoningDetails | { "type": "command_execution" } & CommandExecutionDetails | { "type": "file_change" } & FileChangeDetails | { "type": "mcp_tool_call" } & McpToolCallDetails | { "type": "collab_tool_call" } & CollabToolCallDetails | { "type": "web_search" } & WebSearchDetails | { "type": "todo_list" } & TodoListDetails | { "type": "error" } & ErrorDetails;
