// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaDetails } from "./DeltaDetails";
import type { ItemType } from "./ItemType";

/**
 * Item delta payload for streaming
 */
export type ItemDeltaPayload = { item_type: ItemType, delta: DeltaDetails, };
