// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemDetails } from "./ItemDetails";
import type { ItemType } from "./ItemType";

/**
 * Item updated payload
 */
export type ItemUpdatedPayload = { item_type: ItemType, details: ItemDetails, };
