// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of work item
 */
export type ItemType = "agent_message" | "reasoning" | "command_execution" | "file_change" | "mcp_tool_call" | "collab_tool_call" | "web_search" | "todo_list" | "error";
