// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * MCP tool call result
 */
export type McpResult = { content: Array<JsonValue>, structured_content: JsonValue | null, };
