// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status for MCP tool calls
 */
export type McpStatus = "in_progress" | "completed" | "failed";
