// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpError } from "./McpError";
import type { McpResult } from "./McpResult";
import type { McpStatus } from "./McpStatus";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * MCP tool call details
 */
export type McpToolCallDetails = { server: string, tool: string, arguments: JsonValue, result: McpResult | null, error: McpError | null, status: McpStatus, };
