// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayload } from "./EventPayload";
import type { EventSource } from "./EventSource";

/**
 * Normalized event envelope with universal metadata
 */
export type NormalizedEvent = { 
/**
 * Thread identifier
 */
thread_id: string, 
/**
 * Turn identifier (None for thread-level events)
 */
turn_id: string | null, 
/**
 * Item identifier (None for turn/thread-level events)
 */
item_id: string | null, 
/**
 * Unix timestamp in seconds
 */
timestamp: bigint, 
/**
 * Schema version (starts at 1)
 */
schema_version: number, 
/**
 * Event source for provenance tracking
 */
source: EventSource, 
/**
 * Original event type string for debugging
 */
source_event_type: string, 
/**
 * Event payload
 */
payload: EventPayload, };
