// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status for patch/file changes
 */
export type PatchStatus = "in_progress" | "completed" | "failed";
