// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummaryMetadata } from "./SessionSummaryMetadata";
import type { SummaryNode } from "./SummaryNode";

/**
 * Compact summary for one thread/session timeline.
 */
export type SessionSummary = { schema_version: string, thread_id: string, root_node_id: string, metadata: SessionSummaryMetadata, nodes: Array<SummaryNode>, };
