// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSource } from "./EventSource";

/**
 * Session-level summary metadata.
 */
export type SessionSummaryMetadata = { created_at: bigint, updated_at: bigint, turn_count: number, sources: Array<EventSource>, };
