// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandEvidence } from "./CommandEvidence";
import type { EventReference } from "./EventReference";

/**
 * Evidence pointer collection for a node.
 */
export type SummaryEvidence = { event_refs: Array<EventReference>, file_paths: Array<string>, commands: Array<CommandEvidence>, external_tools: Array<string>, errors: Array<string>, };
