// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummaryEvidence } from "./SummaryEvidence";
import type { SummaryNodeType } from "./SummaryNodeType";
import type { TurnLineage } from "./TurnLineage";

/**
 * Summary node with parent linkage and evidence pointers.
 */
export type SummaryNode = { node_id: string, parent_id: string | null, node_type: SummaryNodeType, title: string, summary: string | null, status: string | null, turn_id: string | null, promoted: boolean, evidence: SummaryEvidence, lineage: TurnLineage | null, };
