// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node types rendered by downstream graph consumers.
 */
export type SummaryNodeType = "session" | "turn" | "plan" | "execution" | "code_changes" | "external_tools" | "error";
