// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Thread started payload
 */
export type ThreadStartedPayload = Record<string, never>;
