// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoItem } from "./TodoItem";

/**
 * Todo list details
 */
export type TodoListDetails = { items: Array<TodoItem>, };
