// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual todo item
 */
export type TodoItem = { text: string, completed: boolean, };
