// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Turn lineage metadata for forks/rollbacks.
 */
export type TurnLineage = { parent_turn_id: string | null, forked_from_thread_id: string | null, started_after_rollback: boolean, was_rolled_back: boolean, };
