// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

/**
 * Turn completed payload
 */
export type TurnCompletedPayload = { usage: TokenUsage, };
