// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Web search details
 */
export type WebSearchDetails = { query: string, action: string | null, };
