import type { AppEvent } from './types'

export const MOCK_EVENTS: AppEvent[] = [
  {
    type: 'TurnStarted',
    turnId: 't1',
    sessionId: 's1',
    userPrompt: 'List all TypeScript files in src/',
    ts: 1000,
  },
  {
    type: 'CommandExecution',
    id: 'e1',
    turnId: 't1',
    cmd: 'find src/ -name "*.ts"',
    exitCode: 0,
    stdout: 'src/main.ts\nsrc/App.tsx\nsrc/lib/types.ts',
    stderr: '',
    ts: 1001,
  },
  {
    type: 'PlanUpdate',
    id: 'e2',
    turnId: 't1',
    text: 'Found 3 TypeScript files — will list them for the user.',
    ts: 1002,
  },
  {
    type: 'TurnComplete',
    turnId: 't1',
    status: 'success',
    ts: 1003,
  },
  {
    type: 'TurnStarted',
    turnId: 't2',
    sessionId: 's1',
    userPrompt: 'Add a console.log to main.ts and run it',
    ts: 2000,
  },
  {
    type: 'McpToolCall',
    id: 'e3',
    turnId: 't2',
    toolName: 'read_file',
    input: { path: 'src/main.ts' },
    output: { content: 'import React from "react"\nimport App from "./App"' },
    status: 'success',
    ts: 2001,
  },
  {
    type: 'PatchApply',
    id: 'e4',
    turnId: 't2',
    filename: 'src/main.ts',
    diff: '@@ -1,2 +1,3 @@\n import React from "react"\n+console.log("hello from AgentCanvas")\n import App from "./App"',
    status: 'success',
    ts: 2002,
  },
  {
    type: 'CommandExecution',
    id: 'e5',
    turnId: 't2',
    cmd: 'node src/main.ts',
    exitCode: 1,
    stdout: '',
    stderr: 'SyntaxError: Cannot use import statement outside a module',
    ts: 2003,
  },
  {
    type: 'TurnComplete',
    turnId: 't2',
    status: 'error',
    ts: 2004,
  },
]
