[package]
name = "codex-feedback"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
codex-protocol = { workspace = true }
sentry = { version = "0.46" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(all(target_os = "linux", target_env = "gnu"))'.dependencies]
openssl-sys = { workspace = true, features = ["vendored"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
